# Lab 01
Welcome to the first lab of CS5130! This lab is meant to help you familiarize yourself with JupyterHub, review Python and `NumPy`, and introduce you to `matplotlib`, a Python visualization library.

To receive credit for a lab, answer all questions correctly and submit before the deadline.

You must submit this assignment to Canvas by the on-time deadline, Wednesday, Sep 23rd, 11:59pm. Please read the syllabus for the grace period policy. Please read the syllabus for the grace period policy. No late submissions beyond the grace period will be accepted. While course staff is happy to help you if you encounter difficulties with submission, we may not be able to respond to late-night requests for assistance (TAs need to sleep, after all!). **We strongly encourage you to plan to submit your work to Canvas several hours before the stated deadline.** This way, you will have ample time to contact staff for submission support.


### Collaboration Policy

Data science is a collaborative activity. While you may talk with others about the labs, we ask that you **write your solutions individually**. If you do discuss the assignments with others please **include their names** below. (It's a good way to learn your classmates' names too!)

**Collaborators**: *list collaborators here* 

<br/><br/>
<hr style="border: 5px solid #003262;" />
<hr style="border: 1px solid #fdb515;" />


## Part 1: Jupyter Tips


### Viewing Documentation

To output the documentation for a function, use the `help` function.

In [1]:
help(print)

Help on built-in function print in module builtins:

print(*args, sep=' ', end='\n', file=None, flush=False)
    Prints the values to a stream, or to sys.stdout by default.

    sep
      string inserted between values, default a space.
    end
      string appended after the last value, default a newline.
    file
      a file-like object (stream); defaults to the current sys.stdout.
    flush
      whether to forcibly flush the stream.



You can also use Jupyter to view function documentation inside your notebook. The function must already be defined in the kernel for this to work.

Below, click your mouse anywhere on the `print` block below and use `Shift` + `Tab` to view the function's documentation. 

In [2]:
print('Welcome to CS5130.')

Welcome to CS5130.


### Importing Libraries and Magic Commands

In CS5130, we will be using common Python libraries to help us process data. By convention, we import all libraries at the very top of the notebook. There are also a set of standard aliases that are used to shorten the library names. Below are some of the libraries that you may encounter throughout the course, along with their respective aliases.

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
plt.style.use('fivethirtyeight')
%matplotlib inline

`%matplotlib inline` is a [Jupyter magic command](https://ipython.readthedocs.io/en/stable/interactive/magics.html) that configures the notebook so that `matplotlib` displays any plots that you draw directly in the notebook rather than to a file, allowing you to view the plots upon executing your code. (Note: In practice, this is no longer necessary, but we're showing it to you now anyway.)

Another useful magic command is `%%time`, which times the execution of that cell. You can use this by writing it as the first line of a cell. (Note that `%%` is used for *cell magic commands* that apply to the entire cell, whereas `%` is used for *line magic commands* that only apply to a single line.)

In [4]:
%%time
lst = []
for i in range(100):
    lst.append(i)

CPU times: user 13 μs, sys: 1 μs, total: 14 μs
Wall time: 16.9 μs


### Keyboard Shortcuts

Even if you are familiar with Jupyter, we strongly encourage you to become proficient with keyboard shortcuts (this will save you time in the future). To learn about keyboard shortcuts, go to **Help --> Keyboard Shortcuts** in the menu above. 

Here are a few that we like:
1. `Ctrl` + `Return` (or `Cmd` + `Return` on Mac): *Evaluate the current cell*
1. `Shift` + `Return`: *Evaluate the current cell and move to the next*
1. `Ctrl` + `+` + `/`: *Comment or uncomment the selected code at once*
1. `ESC` : *command mode* (may need to press before using any of the commands below)
    1. `a` : *create a cell above*
    1. `b` : *create a cell below*
    1. `dd` : *delete a cell*
    1. `z` : *undo the last cell operation*
    1. `m` : *convert a cell to markdown*
    1. `y` : *convert a cell to code*

### Running Cells

Aside from keyboard shortcuts (specifically `Shift` + `Return`), you can also run a single cell by clicking the **Run** button in the top left corner of your notebook. If you hover over the button, you will also find some other options that allow you to run multiple cells. Specifically, the **Run All Above Selected Cell** option is particularly useful for situations wherein you have restarted your notebook and need to run all the cells up until the question you were working on in a lab/homework. 

<br><br>

<hr style="border: 1px solid #fdb515;" />

## Part 2: Prerequisites

It's time to answer some review questions. Each question has a response cell directly below it. Most response cells are followed by a test cell that runs automated tests to check your work. Please don't delete questions, response cells, or test cells. You won't get credit for your work if you do.

If you have extra content in a response cell, such as an example call to a function you're implementing, that's fine. Also, feel free to add cells between the question cells and test cells (or the next cell, for questions without test cases). Any extra cells you add will be considered part of your submission. Finally, when you finish an assignment, make sure to "restart and run all cells" to ensure everything works properly. 

Note that for labs, on-time submissions that pass all the test cases will receive full credit. However, for homeworks, test cells don't always confirm that your response is correct. They are meant to give you some useful feedback, but it's your responsibility to ensure your response answers the question correctly. There may be other tests that we run when scoring your notebooks. We **strongly recommend** that you check your solutions yourself rather than just relying on the test cells.

### Python

Python is the main programming language we'll use in the course. We will learn across this semester and we will cover general Python syntax. If any of the following exercises are challenging, please review one or more of the following materials.

- **[Python Tutorial](https://docs.python.org/3.8/tutorial/)**: Introduction to Python from the creators of Python.
- **[Composing Programs Chapter 1](https://www.composingprograms.com/pages/11-getting-started.html)**: This is more of an introduction to programming with Python.
- **[Advanced Crash Course](http://cs231n.github.io/python-numpy-tutorial/)**: A fast crash course which assumes some programming background.

### `NumPy`

`NumPy` is the numerical computing module which we will learn to use for this course. Here's a quick recap of `NumPy`. For more review, read the following materials.

- **[NumPy Quick Start Tutorial](https://numpy.org/doc/stable/user/quickstart.html)**
- **[DS100 NumPy Review](http://ds100.org/fa17/assets/notebooks/numpy/Numpy_Review.html)**
- **[Stanford CS231n NumPy Tutorial](http://cs231n.github.io/python-numpy-tutorial/#numpy)**
- **[The Data 8 Textbook Chapter on NumPy](https://www.inferentialthinking.com/chapters/05/1/Arrays)**

# Initialize Otter for Auto Grading


In [5]:
## Use pip install otter-grader to install otter
import otter
grader = otter.Notebook("Lab01.ipynb")

<br/><br/>

---

### Question 1 (10')

The core of `NumPy` is the array. Like Python lists, arrays store data; however, they store data in a more efficient manner. In many cases, this allows for faster computation and data manipulation.We use `np.array` to create an array. It takes a sequence, such as a list or range. 

Below, create an array `arr` containing the values 1, 2, 3, 4, and 5 (in that order)

In [6]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [7]:
# grader.check("q1")

In addition to values in the array, we can access attributes such as shape and data type. A full list of attributes can be found [here](https://docs.scipy.org/doc/numpy-1.15.0/reference/arrays.ndarray.html#array-attributes).


In [8]:
arr[3]

np.int64(4)

In [9]:
arr[2:4]

array([3, 4])

In [10]:
arr.shape

(5,)

In [11]:
arr.dtype

dtype('int64')

Arrays, unlike Python lists, cannot store items of different data types.

In [12]:
# A regular Python list can store items of different data types
[1, '3']

[1, '3']

In [13]:
# Arrays will convert everything to the same data type
np.array([1, '3'])

array(['1', '3'], dtype='<U21')

In [14]:
# Another example of array type conversion
np.array([5, 8.3])

array([5. , 8.3])

Arrays are also useful in performing *vectorized operations*. Given two or more arrays of equal length, arithmetic will perform element-wise computations across the arrays. 

For example, observe the following:

In [15]:
# Python list addition will concatenate the two lists
[1, 2, 3] + [4, 5, 6]

[1, 2, 3, 4, 5, 6]

In [16]:
# NumPy array addition will add them element-wise
np.array([1, 2, 3]) + np.array([4, 5, 6])

array([5, 7, 9])

### Question 2 (10')
Write a function `summation` that evaluates the following summation for $n \geq 1$:

$$\sum_{i=1}^{n} i^3 + 3 i^2$$

**Note**: You should not use `for` loops in your solution. Check the [NumPy documentation](https://numpy.org/doc/1.23/reference/index.html). If you're stuck, try a search engine! Searching the web for examples of how to use modules is very common in data science. You may find `np.arange` helpful for this question!

In [17]:
def summation(n):
    """Compute the summation i^3 + 3 * i^2 for 1 <= i <= n."""
    if n >= 1:
        i = np.arange(1, n+1)
        return np.sum(i**3 + 3*(i**2))
    else:
        return -1

In [18]:
# grader.check("q2")

<br/><br/>

---

### Question 2b

Write a function `elementwise_array_sum` that computes the square of each value in `list_1`, the cube of each value in `list_2`, then returns a list containing the element-wise sum of these results. Assume that `list_1` and `list_2` have the same number of elements, do not use for loops.

The input parameters will both be **Python lists**, so you may need to convert the lists into arrays before performing your operations. The output should be a **`NumPy` array.**

In [19]:
def elementwise_array_sum(list_1, list_2):
    """Compute x^2 + y^3 for each x, y in list_1, list_2. 
    
    Assume list_1 and list_2 have the same length.
    
    Return a NumPy array.
    """
    assert len(list_1) == len(list_2), "both args must have the same number of elements"
    list_1 = np.array(list_1, dtype='float64')
    list_2 = np.array(list_2, dtype='float64')
    return (list_1**2) + (list_2**3)

In [20]:
# grader.check("q2b")

You might have been told that Python is slow, but array arithmetic is carried out very fast, even for large arrays. Below is an implementation of the above code that does not use `NumPy` arrays.

In [21]:
def elementwise_list_sum(list_1, list_2):
    """Compute x^2 + y^3 for each x, y in list_1, list_2.

    Assume list_1 and list_2 have the same length.
    """

    return [x ** 2 + y ** 3 for x, y in zip(list_1, list_2)]

For ten numbers, `elementwise_list_sum` and `elementwise_array_sum` both take a similar amount of time.


In [22]:
sample_list_1 = list(range(10))
sample_array_1 = np.arange(10)

In [23]:
%%time
elementwise_list_sum(sample_list_1, sample_list_1)

CPU times: user 9 μs, sys: 0 ns, total: 9 μs
Wall time: 11 μs


[0, 2, 12, 36, 80, 150, 252, 392, 576, 810]

In [24]:
%%time
elementwise_array_sum(sample_array_1, sample_array_1)

CPU times: user 72 μs, sys: 9 μs, total: 81 μs
Wall time: 85.4 μs


array([  0.,   2.,  12.,  36.,  80., 150., 252., 392., 576., 810.])

The time difference seems negligible for a list/array of size 10; depending on your setup, you may even observe that `elementwise_list_sum` executes faster than `elementwise_array_sum`! However, we will commonly be working with much larger datasets:

In [25]:
sample_list_2 = list(range(100000))
sample_array_2 = np.arange(100000)

In [26]:
%%time
elementwise_list_sum(sample_list_2, sample_list_2)
# The semicolon hides the output
; 

CPU times: user 32.5 ms, sys: 1.08 ms, total: 33.6 ms
Wall time: 33.4 ms


In [27]:
%%time
elementwise_array_sum(sample_array_2, sample_array_2)
# The semicolon hides the output
;

CPU times: user 3.79 ms, sys: 975 μs, total: 4.77 ms
Wall time: 3.5 ms


With the larger dataset, we see that using `NumPy` results in code that executes over 50 times faster! Throughout this course (and in the real world), you will find that writing efficient code will be important; arrays and vectorized operations are the most common way of making Python programs run quickly.

<br/><br/>

---

### Question 2c
Recall the formula for population variance below:

$$\sigma^2 = \frac{\sum_{i=1}^N (x_i - \mu)^2}{N}$$

Complete the functions below to compute the population variance of `population`, an array of numbers. For this question, **do not use built-in  `NumPy ` functions, such as `np.var`.** Again, avoid using `for` loops!

In [28]:
def mean(population):
    """
    Returns the mean of population (mu)
    
    Keyword arguments:
    population -- a numpy array of numbers
    """
    # Calculate the mean of a population
    return np.sum(population)/len(population)

def variance(population):
    """
    Returns the variance of population (sigma squared)
    
    Keyword arguments:
    population -- a numpy array of numbers
    """
    u = mean(population)
    return (np.sum((population-u)**2))/len(population)
    ...

In [29]:
# grader.check("q2c")

<br/><br/>

---

### Question 2d

Given the array `random_arr`, assign `valid_values` to an array containing all values $x$ such that $2x^4 > 1$.

**Note**: You should not use `for` loops in your solution. Instead, look at  `NumPy`'s documentation on [Boolean Indexing](https://numpy.org/doc/stable/user/basics.indexing.html#boolean-array-indexing). Documentation can be very intimidating at first glance, but don't worry, that's completely okay, one of the goals of this class is to build familiarity with reading the documentation of data science tools. Ask for help if needed, we're always there for you!

In [30]:
np.random.seed(42)
random_arr = np.random.rand(60)
valid_values = random_arr[2 * random_arr**4 > 1]
valid_values

array([0.95071431, 0.86617615, 0.96990985, 0.94888554, 0.96563203,
       0.9093204 , 0.96958463, 0.93949894, 0.89482735, 0.92187424])

In [31]:
# grader.check("q2d")

<br><br>

<hr style="border: 1px solid #fdb515;" />

## Part 3: Plotting
Here we explore plotting using `matplotlib` and `NumPy`.

### Question 3 (10')



Consider the function $f(x) = x^2$ for $-\infty < x < \infty$.

<br/><br/>

---

### Question 3a
Find the equation of the tangent line to $f$ at $x = 0$.

Type your solution, such that it looks like the serif font used to display the math expressions in the sentences above.

**HINT**: You can click any text cell to see the raw Markdown syntax. If you choose to use LaTeX, our Latex tips guide is linked [here](https://ds100.org/sp22/resources/assets/hw/latex_tips.pdf), but by no means do you _need_ to use it.

The tangent line at a point is the straight line that touches the curve there and has the same slope as the curve. So I need two things: the point on the curve, and the slope at that point.

Differentiating $f(x) = x^2$ gives
$$f'(x) = 2x$$

At $x = 0$, the slope is $f'(0) = 2(0) = 0$ and the point on the curve is $(0, f(0)) = (0, 0)$.

Using the point-slope form $y - y_1 = m(x - x_1)$:
$$y - 0 = 0(x - 0)$$
$$y = 0$$

So the tangent line at $x = 0$ is the horizontal line $y = 0$, which is the $x$-axis.

<br/><br/>

---

### Question 3b

Find the equation of the tangent line to $f$ at $x = 8$. 

Same derivative, different point. At $x = 8$, the slope is $f'(8) = 2(8) = 16$ and the point on the curve is $(8, f(8)) = (8, 64)$.

$$y - 64 = 16(x - 8)$$
$$y - 64 = 16x - 128$$
$$y = 16x - 64$$

<br/><br/>

---

### Question 3c

Write code to plot the function $f$, the tangent line at $x=8$, and the tangent line at $x=0$.

Set the range of the x-axis to (-15, 15) and the range of the y-axis to (-100, 300) and the figure size to (4,4).

Your resulting plot should look like this (it's okay if the colors in your plot don't match with ours, as long as they're all different colors):

<img src="derivative.png" align="center"/>

You should use the `plt.plot` function to plot lines. You may find the following functions useful (click on them to read about their documentation!):

- [`plt.plot(..)`](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.plot.html)
- [`plt.figure(figsize=..)`](https://stackoverflow.com/questions/332289/how-do-you-change-the-size-of-figures-drawn-with-matplotlib)
- [`plt.ylim(..)`](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.ylim.html)
- [`plt.axhline(..)`](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.axhline.html)

x = np.linspace(-15, 15, 1000)
y = x**2

plt.figure(figsize=(4,4))
plt.plot(x,y)
plt.axline((0, 0), slope=0, color="red")
plt.axline((8, 64), slope=16, color="yellow")
plt.ylim(-100, 300)
plt.xlim(-15, 15)

<br/><br/>
<hr style="border: 5px solid #003262;" />
<hr style="border: 1px solid #fdb515;" />

## Congratulations! You have finished Lab 1!

## Submission

Make sure you have run all cells in your notebook in order before running the cell below, so that all images/graphs appear in the output. **Please save before submiting!**

In [32]:
# grader.check_all()

In [33]:
# grader.export(pdf=False, force_save=True)